[package]
name = "hyprshade"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/loqusion/hyprshade"

[dependencies]
clap = { version = "4.5.9", features = ["cargo", "derive", "wrap_help"] }
clap_derive = "4.5.8"
color-eyre = "0.6.3"
derive_more = "0.99.18"
directories = "5.0.1"
eyre = "0.6.12"
mustache = "0.9.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
thiserror = "1.0.63"
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.10.1"

[profile.release]
opt-level = "z"
strip = true
lto = true
