[package]
name = "hyprshade"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/loqusion/hyprshade"

[dependencies]
clap = { version = "4.5.8", features = ["cargo", "derive", "wrap_help"] }
clap_derive = "4.5.8"
color-eyre = "0.6.3"
eyre = "0.6.12"
mustache = "0.9.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
thiserror = "1.0.61"

[profile.release]
opt-level = "z"
strip = true
lto = true
