[package]
name = "proc_macros"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
quote = "1.0.36"
syn = { version = "2.0.74", features = ["full"] }

[lib]
proc-macro = true
