name: CI

on:
  push:
    branches:
      - main
      - ci*
  pull_request: {}

env:
  RUST_BACKTRACE: 1
  rust_stable: stable

jobs:
  basics:
    name: basic checks
    runs-on: ubuntu-latest
    needs:
      - clippy
      - fmt
    steps:
      - run: exit 0

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo clippy --workspace --lib --bins --tests --examples --all-features

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt --check
        run: cargo fmt --all --check --verbose

  test:
    name: test
    needs: basics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable}}
      - uses: Swatinem/rust-cache@v2
      - run: cargo xtask test
